USERS_REST_SERVER_MAINCLASS=tp.impl.servers.rest.UsersRestServer
USERS_REST_PORT=3456
USERS_SOAP_SERVER_MAINCLASS=tp.impl.servers.soap.UsersSoapServer
USERS_SOAP_PORT=13456
USERS_EXTRA_ARGS=files-sdrules###directory-connectiontimeout
DIR_REST_SERVER_MAINCLASS=tp.impl.servers.rest.DirectoryRestServer
DIR_REST_PORT=4567
DIR_SOAP_SERVER_MAINCLASS=tp.impl.servers.soap.DirectorySoapServer
DIR_SOAP_PORT=14567
DIR_EXTRA_ARGS=files-testerrocks###users-connectiontimeout
FILES_REST_SERVER_MAINCLASS=tp.impl.servers.rest.FilesRestServer
FILES_REST_PORT=5678
FILES_SOAP_SERVER_MAINCLASS=tp.impl.servers.soap.FilesSoapServer
FILES_SOAP_PORT=15678
FILES_EXTRA_ARGS=directory-testerrocks###users-sdrules
DISCOVERY_MULTICAST_IP=226.226.226.226
DISCOVERY_MULTICAST_PORT=2262
USERS_SERVER_KEYSTORE=usersserver.jks
USERS_SERVER_KEYSTORE_PWD=777users
DIR_SERVER_KEYSTORE=dirserver.jks
DIR_SERVER_KEYSTORE_PWD=777directory
FILES_SERVER_KEYSTORE=filesserver.jks
FILES_SERVER_KEYSTORE_PWD=777files
CLIENT_TRUSTSTORE=client-ts.jks
CLIENT_TRUSTSTORE_PWD=changeit
FILES_PROXY_SERVER_MAINCLASS=tp.impl.servers.rest.FilesRestDropboxServer
FILES_PROXY_PORT=5679
FILES_PROXY_EXTRA_ARGS=apiKey-tv881188xx6d6ly###apiSecret-z0etm4xln8eg87i###accessTokenStr-sl.BJFBeB35hLGDApnKqqsAga-UtJwm6T9RMc8-ZDJmyVP_OrFwBz52iBLmyCOHqZNFCTfY-w9KhCIgCrvRxm3e-Cgcy7YHeBWruoAA1pmOxrDF_BzAmy6JgW1ecz9gHr3Q4He03E8
DIR_REP_SERVER_MAINCLASS=tp.impl.servers.rest.DirectoryReplicationRestServer
DIR_REP_PORT=4568
DIR_REP_EXTRA_ARGS_FIRST=files-testerrocks###users-connectiontimeout
DIR_REP_EXTRA_ARGS_OTHER=
